apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cp6x60vnb-nodejs 
  janus-idp.io/tekton: cp6x60vnb-nodejs
  backstage.io/kubernetes-id: cp6x60vnb-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cp6x60vnb-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  