apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cp6x60vnb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cp6x60vnb-nodejs 
  name: cp6x60vnb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cp6x60vnb-nodejs 
